### ISSUE TITLE
Wrong generated path for windows

### ISSUE THREAD

**Issue by yuriy-malkov** [lightbend/kalix-javascript-sdk#404]
Error:
```
> npm run start

> customer-registry@0.0.2 start C:\repositories\customer-registry
> node src/index.js

internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

    at moduleResolve (internal/modules/esm/resolve.js:773:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:887:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:76:40)
    at link (internal/modules/esm/module_job.js:75:36) {
  code: 'ERR_INVALID_MODULE_SPECIFIER'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! customer-registry@0.0.2 start: `node src/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the customer-registry@0.0.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Issue:
	- improper path specified for windows in generated\index.js
```
	import customer from "..\..\src\customer.js";
```

Resolution:
	- path for windows should be changed to in generated\index.js
```
 import customer from "../../src/customer.js";
```

After manual change:
```
 > npm run start

> customer-registry@0.0.2 start C:\repositories\customer-registry
> node src/index.js

Server bound on port: 8080
Kalix service started on 127.0.0.1:8080
```

**Comment by franciscolopezsancho** [comment]
released
